package client;

import javax.swing.Timer;
import server.GameCommand;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author wygon
 */
public class SearchingGameWindow extends javax.swing.JFrame {

    /**
     * Creates new form SearchingGameWindow
     */
    private CardPanel ui;
    private Timer timer;
    private int stime;
    
    public SearchingGameWindow(CardPanel cp) {
        this.ui = cp;
        setLocationRelativeTo(cp);
        initComponents();
        stime = 0;
        timer =  new Timer(1000, e-> {
            stime++;
            int minutes = stime / 60;
            int seconds = stime % 60;
           String format = String.format("%02d:%02d", minutes, seconds);
           waitingTimerLabel.setText(format);
        });
    }
    public void timerStart() {
        stime = 0;
        timer.start();
    }
    public void timerStop(){
        waitingTimerLabel.setText("00:00");
        timer.stop();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        returnToLobby = new javax.swing.JButton();
        waitingTimerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Searching opponent");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        returnToLobby.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        returnToLobby.setText("RETURN");
        returnToLobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToLobbyActionPerformed(evt);
            }
        });

        waitingTimerLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        waitingTimerLabel.setText("00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(returnToLobby, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(waitingTimerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waitingTimerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(returnToLobby, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnToLobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToLobbyActionPerformed
        // TODO add your handling code here:
        ui.client.sendMessage(
                GameCommand.FIND_CANCEL + ">" +
                        ui.client.myGameId
        );
    }//GEN-LAST:event_returnToLobbyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton returnToLobby;
    private javax.swing.JLabel waitingTimerLabel;
    // End of variables declaration//GEN-END:variables
}
